/** Built-in ISO 4217 currencies with Arabic label and flag (or regional) emoji. */

export interface CurrencyInfo {
  code: string;
  nameAr: string;
  flag: string;
}

const DATA: CurrencyInfo[] = [
  { code: "AED", nameAr: "درهم إماراتي", flag: "🇦🇪" },
  { code: "AFN", nameAr: "أفغاني", flag: "🇦🇫" },
  { code: "ALL", nameAr: "ليك ألباني", flag: "🇦🇱" },
  { code: "AMD", nameAr: "درام أرميني", flag: "🇦🇲" },
  { code: "ANG", nameAr: "غيلدر أنتيلي", flag: "🇨🇼" },
  { code: "AOA", nameAr: "كوانزا أنغولي", flag: "🇦🇴" },
  { code: "ARS", nameAr: "بيزو أرجنتيني", flag: "🇦🇷" },
  { code: "AUD", nameAr: "دولار أسترالي", flag: "🇦🇺" },
  { code: "AWG", nameAr: "فلورين أروبي", flag: "🇦🇼" },
  { code: "AZN", nameAr: "مانات أذربيجاني", flag: "🇦🇿" },
  { code: "BAM", nameAr: "مارك قابل للتحويل", flag: "🇧🇦" },
  { code: "BBD", nameAr: "دولار بربادوسي", flag: "🇧🇧" },
  { code: "BDT", nameAr: "تاكا بنغلاديشية", flag: "🇧🇩" },
  { code: "BGN", nameAr: "ليف بلغاري", flag: "🇧🇬" },
  { code: "BHD", nameAr: "دينار بحريني", flag: "🇧🇭" },
  { code: "BIF", nameAr: "فرنك بوروندي", flag: "🇧🇮" },
  { code: "BMD", nameAr: "دولار برمودي", flag: "🇧🇲" },
  { code: "BND", nameAr: "دولار بروني", flag: "🇧🇳" },
  { code: "BOB", nameAr: "بوليفيانو", flag: "🇧🇴" },
  { code: "BRL", nameAr: "ريال برازيلي", flag: "🇧🇷" },
  { code: "BSD", nameAr: "دولار باهامي", flag: "🇧🇸" },
  { code: "BTN", nameAr: "نولتروم بوتاني", flag: "🇧🇹" },
  { code: "BWP", nameAr: "بولا بوتسواني", flag: "🇧🇼" },
  { code: "BYN", nameAr: "روبل بلاروسي", flag: "🇧🇾" },
  { code: "BZD", nameAr: "دولار بليزي", flag: "🇧🇿" },
  { code: "CAD", nameAr: "دولار كندي", flag: "🇨🇦" },
  { code: "CDF", nameAr: "فرنك كونغولي", flag: "🇨🇩" },
  { code: "CHF", nameAr: "فرنك سويسري", flag: "🇨🇭" },
  { code: "CLP", nameAr: "بيزو تشيلي", flag: "🇨🇱" },
  { code: "CNY", nameAr: "يوان صيني", flag: "🇨🇳" },
  { code: "COP", nameAr: "بيزو كولومبي", flag: "🇨🇴" },
  { code: "CRC", nameAr: "كولون كوستريكي", flag: "🇨🇷" },
  { code: "CUP", nameAr: "بيزو كوبي", flag: "🇨🇺" },
  { code: "CVE", nameAr: "إسكودو رأس أخضر", flag: "🇨🇻" },
  { code: "CZK", nameAr: "كورونا تشيكية", flag: "🇨🇿" },
  { code: "DJF", nameAr: "فرنك جيبوتي", flag: "🇩🇯" },
  { code: "DKK", nameAr: "كرونة دنماركية", flag: "🇩🇰" },
  { code: "DOP", nameAr: "بيزو دومينيكاني", flag: "🇩🇴" },
  { code: "DZD", nameAr: "دينار جزائري", flag: "🇩🇿" },
  { code: "EGP", nameAr: "جنيه مصري", flag: "🇪🇬" },
  { code: "ERN", nameAr: "ناكفا إريتري", flag: "🇪🇷" },
  { code: "ETB", nameAr: "بير إثيوبي", flag: "🇪🇹" },
  { code: "EUR", nameAr: "يورو", flag: "🇪🇺" },
  { code: "FJD", nameAr: "دولار فيجي", flag: "🇫🇯" },
  { code: "FKP", nameAr: "جنيه جزر فوكلاند", flag: "🇫🇰" },
  { code: "GBP", nameAr: "جنيه إسترليني", flag: "🇬🇧" },
  { code: "GEL", nameAr: "لاري جورجي", flag: "🇬🇪" },
  { code: "GHS", nameAr: "سيدي غاني", flag: "🇬🇭" },
  { code: "GIP", nameAr: "جنيه جبل طارق", flag: "🇬🇮" },
  { code: "GMD", nameAr: "دالاسي غامبي", flag: "🇬🇲" },
  { code: "GNF", nameAr: "فرنك غيني", flag: "🇬🇳" },
  { code: "GTQ", nameAr: "كتزال غواتيمالي", flag: "🇬🇹" },
  { code: "GYD", nameAr: "دولار غياني", flag: "🇬🇾" },
  { code: "HKD", nameAr: "دولار هونغ كونغ", flag: "🇭🇰" },
  { code: "HNL", nameAr: "لمبيرا هندوراسية", flag: "🇭🇳" },
  { code: "HRK", nameAr: "كونا كرواتية", flag: "🇭🇷" },
  { code: "HTG", nameAr: "غورد هايتي", flag: "🇭🇹" },
  { code: "HUF", nameAr: "فورنت مجري", flag: "🇭🇺" },
  { code: "IDR", nameAr: "روبية إندونيسية", flag: "🇮🇩" },
  { code: "ILS", nameAr: "شيكل جديد", flag: "🇮🇱" },
  { code: "INR", nameAr: "روبية هندية", flag: "🇮🇳" },
  { code: "IQD", nameAr: "دينار عراقي", flag: "🇮🇶" },
  { code: "IRR", nameAr: "ريال إيراني", flag: "🇮🇷" },
  { code: "ISK", nameAr: "كرونة أيسلندية", flag: "🇮🇸" },
  { code: "JMD", nameAr: "دولار جامايكي", flag: "🇯🇲" },
  { code: "JOD", nameAr: "دينار أردني", flag: "🇯🇴" },
  { code: "JPY", nameAr: "ين ياباني", flag: "🇯🇵" },
  { code: "KES", nameAr: "شيلينغ كيني", flag: "🇰🇪" },
  { code: "KGS", nameAr: "سوم قيرغيزستاني", flag: "🇰🇬" },
  { code: "KHR", nameAr: "ريال كمبودي", flag: "🇰🇭" },
  { code: "KMF", nameAr: "فرنك جزر القمر", flag: "🇰🇲" },
  { code: "KPW", nameAr: "وون كوري شمالي", flag: "🇰🇵" },
  { code: "KRW", nameAr: "وون كوري جنوبي", flag: "🇰🇷" },
  { code: "KWD", nameAr: "دينار كويتي", flag: "🇰🇼" },
  { code: "KYD", nameAr: "دولار جزر كايمان", flag: "🇰🇾" },
  { code: "KZT", nameAr: "تينغ كازاخستاني", flag: "🇰🇿" },
  { code: "LAK", nameAr: "كيب لاوسي", flag: "🇱🇦" },
  { code: "LBP", nameAr: "ليرة لبنانية", flag: "🇱🇧" },
  { code: "LKR", nameAr: "روبية سريلانكية", flag: "🇱🇰" },
  { code: "LRD", nameAr: "دولار ليبيري", flag: "🇱🇷" },
  { code: "LSL", nameAr: "لوتي ليسوتو", flag: "🇱🇸" },
  { code: "LYD", nameAr: "دينار ليبي", flag: "🇱🇾" },
  { code: "MAD", nameAr: "درهم مغربي", flag: "🇲🇦" },
  { code: "MDL", nameAr: "ليو مولدوفي", flag: "🇲🇩" },
  { code: "MGA", nameAr: "أرياري مدغشقري", flag: "🇲🇬" },
  { code: "MKD", nameAr: "دينار مقدوني", flag: "🇲🇰" },
  { code: "MMK", nameAr: "كيات ميانماري", flag: "🇲🇲" },
  { code: "MNT", nameAr: "توغروغ منغولي", flag: "🇲🇳" },
  { code: "MOP", nameAr: "باتاكا ماكاوية", flag: "🇲🇴" },
  { code: "MRU", nameAr: "أوقية موريتانية", flag: "🇲🇷" },
  { code: "MUR", nameAr: "روبية موريشيوسية", flag: "🇲🇺" },
  { code: "MVR", nameAr: "روفية مالديفية", flag: "🇲🇻" },
  { code: "MWK", nameAr: "كواشا مالاوي", flag: "🇲🇼" },
  { code: "MXN", nameAr: "بيزو مكسيكي", flag: "🇲🇽" },
  { code: "MYR", nameAr: "رينغيت ماليزي", flag: "🇲🇾" },
  { code: "MZN", nameAr: "متكال موزمبيقي", flag: "🇲🇿" },
  { code: "NAD", nameAr: "دولار ناميبي", flag: "🇳🇦" },
  { code: "NGN", nameAr: "نايرا نيجيري", flag: "🇳🇬" },
  { code: "NIO", nameAr: "كوردوبا نيكاراغوي", flag: "🇳🇮" },
  { code: "NOK", nameAr: "كرونة نرويجية", flag: "🇳🇴" },
  { code: "NPR", nameAr: "روبية نيبالية", flag: "🇳🇵" },
  { code: "NZD", nameAr: "دولار نيوزيلندي", flag: "🇳🇿" },
  { code: "OMR", nameAr: "ريال عُماني", flag: "🇴🇲" },
  { code: "PAB", nameAr: "بالبوا بنمي", flag: "🇵🇦" },
  { code: "PEN", nameAr: "سول بيروفي", flag: "🇵🇪" },
  { code: "PGK", nameAr: "كينا بابوا غينيا", flag: "🇵🇬" },
  { code: "PHP", nameAr: "بيزو فلبيني", flag: "🇵🇭" },
  { code: "PKR", nameAr: "روبية باكستانية", flag: "🇵🇰" },
  { code: "PLN", nameAr: "زلوتي بولندي", flag: "🇵🇱" },
  { code: "PYG", nameAr: "غواراني باراغواي", flag: "🇵🇾" },
  { code: "QAR", nameAr: "ريال قطري", flag: "🇶🇦" },
  { code: "RON", nameAr: "ليو روماني", flag: "🇷🇴" },
  { code: "RSD", nameAr: "دينار صربي", flag: "🇷🇸" },
  { code: "RUB", nameAr: "روبل روسي", flag: "🇷🇺" },
  { code: "RWF", nameAr: "فرنك رواندي", flag: "🇷🇼" },
  { code: "SAR", nameAr: "ريال سعودي", flag: "🇸🇦" },
  { code: "SBD", nameAr: "دولار جزر سليمان", flag: "🇸🇧" },
  { code: "SCR", nameAr: "روبية سيشيلية", flag: "🇸🇨" },
  { code: "SDG", nameAr: "جنيه سوداني", flag: "🇸🇩" },
  { code: "SEK", nameAr: "كرونة سويدية", flag: "🇸🇪" },
  { code: "SGD", nameAr: "دولار سنغافوري", flag: "🇸🇬" },
  { code: "SHP", nameAr: "جنيه سانت هيلينا", flag: "🇸🇭" },
  { code: "SLE", nameAr: "ليون سيراليوني", flag: "🇸🇱" },
  { code: "SOS", nameAr: "شلن صومالي", flag: "🇸🇴" },
  { code: "SRD", nameAr: "دولار سورينامي", flag: "🇸🇷" },
  { code: "SSP", nameAr: "جنيه جنوب السودان", flag: "🇸🇸" },
  { code: "STN", nameAr: "دوبرا ساو تومي", flag: "🇸🇹" },
  { code: "SVC", nameAr: "كولون سلفادوري", flag: "🇸🇻" },
  { code: "SYP", nameAr: "ليرة سورية", flag: "🇸🇾" },
  { code: "SZL", nameAr: "ليلانجيني سوازيلندي", flag: "🇸🇿" },
  { code: "THB", nameAr: "بات تايلاندي", flag: "🇹🇭" },
  { code: "TJS", nameAr: "سوموني طاجيكي", flag: "🇹🇯" },
  { code: "TMT", nameAr: "مانات تركمانستاني", flag: "🇹🇲" },
  { code: "TND", nameAr: "دينار تونسي", flag: "🇹🇳" },
  { code: "TOP", nameAr: "بانغا تونغي", flag: "🇹🇴" },
  { code: "TRY", nameAr: "ليرة تركية", flag: "🇹🇷" },
  { code: "TTD", nameAr: "دولار ترينيداد", flag: "🇹🇹" },
  { code: "TWD", nameAr: "دولار تايواني", flag: "🇹🇼" },
  { code: "TZS", nameAr: "شيلينغ تنزاني", flag: "🇹🇿" },
  { code: "UAH", nameAr: "هريفنيا أوكرانية", flag: "🇺🇦" },
  { code: "UGX", nameAr: "شيلينغ أوغندي", flag: "🇺🇬" },
  { code: "USD", nameAr: "دولار أمريكي", flag: "🇺🇸" },
  { code: "UYU", nameAr: "بيزو أوروغواي", flag: "🇺🇾" },
  { code: "UZS", nameAr: "سوم أوزبكي", flag: "🇺🇿" },
  { code: "VES", nameAr: "بوليفار فنزويلي", flag: "🇻🇪" },
  { code: "VND", nameAr: "دونغ فيتنامي", flag: "🇻🇳" },
  { code: "VUV", nameAr: "فانواتو فاتو", flag: "🇻🇺" },
  { code: "WST", nameAr: "تالا ساموي", flag: "🇼🇸" },
  { code: "XAF", nameAr: "فرنك وسط أفريقيا", flag: "🇨🇲" },
  { code: "XCD", nameAr: "دولار شرق الكاريبي", flag: "🇦🇬" },
  { code: "XOF", nameAr: "فرنك غرب أفريقيا", flag: "🇸🇳" },
  { code: "XPF", nameAr: "فرنك سي إف بي", flag: "🇵🇫" },
  { code: "YER", nameAr: "ريال يمني", flag: "🇾🇪" },
  { code: "ZAR", nameAr: "راند جنوب أفريقيا", flag: "🇿🇦" },
  { code: "ZMW", nameAr: "الكوا تشا زامبي", flag: "🇿🇲" },
  { code: "ZWL", nameAr: "دولار زيمبابوي", flag: "🇿🇼" },
];

const byCode = new Map(DATA.map((c) => [c.code, c]));

export function listCurrenciesSorted(): CurrencyInfo[] {
  return [...DATA].sort((a, b) => a.code.localeCompare(b.code));
}

export function getCurrencyInfo(code: string): CurrencyInfo {
  const c = code.trim().toUpperCase();
  return (
    byCode.get(c) ?? {
      code: c,
      nameAr: c,
      flag: "💱",
    }
  );
}
